// Export a generated build in the game's own hero-build JSON (the CMsgHeroBuild shape the game coordinator serves,
// as mirrored by api.deadlock-api.com/v1/builds). Categories are the build's phases; each mod is an item id. The game
// has no import button for this file: it is the payload a Steam game-coordinator upload (ClientToGCUpdateHeroBuild)
// would send, and what community build sites accept.
import type { Build, Phase } from '../types';

const PHASE_NAME: Record<Phase, string> = { early: 'Early Game', mid: 'Mid Game', late: 'Late Game' };

export function toGameBuild(build: Build, heroName: string, fetchedAt?: string) {
  const phases = (['early', 'mid', 'late'] as Phase[]).filter((p) => build.items.some((b) => b.phase === p));
  const abilityOrder = build.abilityOrder.map((s) => s.ability.id);
  return {
    hero_build: {
      hero_id: build.heroId, hero_build_id: 0, author_account_id: 0,
      last_updated_timestamp: Math.floor(Date.now() / 1000), publish_timestamp: null,
      name: `${heroName}: ${build.name}`.slice(0, 64),
      description: `${build.tagline}\nGenerated by Deadlock Build Optimizer${fetchedAt ? ` from data fetched ${fetchedAt}` : ''}. Numbers in the notes are buy order.`,
      language: 0, version: 1, origin_build_id: 0, tags: [], development_build: null,
      details: {
        mod_categories: phases.map((p) => ({
          name: PHASE_NAME[p], width: 790.5, height: 150.75, description: '',
          mods: build.items.filter((b) => b.phase === p).map((b) => ({
            ability_id: b.item.id, annotation: `#${b.order}${b.upgradesFrom ? `, upgrades ${b.upgradesFrom.name}` : ''}`,
            required_flex_slots: null, sell_priority: null, imbue_target_ability_id: null,
          })),
          optional: null,
        })),
        ability_order: { currency_changes: abilityOrder.map((id, i) => ({ ability_id: id, currency_type: 1, delta: [0, 1, 2, 5][build.abilityOrder[i].kind === 'unlock' ? 0 : Number(build.abilityOrder[i].kind.slice(-1))] })) },
      },
    },
  };
}

export const downloadText = (name: string, text: string, type = 'application/json') => {
  const a = document.createElement('a');
  a.href = URL.createObjectURL(new Blob([text], { type })); a.download = name; a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 1000);
};
